version: '3.8'

services:
  db:
    image: postgres:11
    env_file:
      - .env
    volumes:
      - /opt/postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
